# Generated by Django 6.1.1 on 2026-09-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
